name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: Rabo-Linux-Production

trigger:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: yapl
      type: git
      name: Maui/yapl

variables:
  - group: nexus credentials
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: BuildOthers
        displayName: Build Other branch
        timeoutInMinutes: 15
        condition: and(succeeded(), eq(variables.isMain, false))
        pool:
          name: Rabo-Linux-Production
        steps:
          - template: templates/maven-build-others-branch.yml

      - job: BuildMaster
        displayName: Build Main
        timeoutInMinutes: 15
        condition: and(succeeded(), eq(variables.isMain, true))
        pool:
          name: Rabo-Linux-Production
        steps:
          - template: /pipeline/continuous-integration.yml@yapl
            parameters:
              mavenSettingsFile: 'settings.xml'
              jacocoVersion: '0.8.11'
              mavenGoals: '-Dnexus.username=$(nexus.username) -Dnexus.password=$(nexus.password)'
              javaVersion: '1.17'
              applicationName: 'rdc-kafka-standalone'
              sonarEnabled: false
              fortify:
                enabled: false
              nexusIq:
                enabled: false
              featureTests:
                enabled: false

  - stage: Docker
    jobs:
      - job: Docker_push
        condition: and(succeeded(), eq(variables.isMain, true))
        displayName: Build and Push Kafka Docker Image
        steps:
          - task: DownloadSecureFile@1
            name: settingsfile
            displayName: Download settings file
            inputs:
              secureFile: 7c399f5c-a5f4-4f17-a17c-1e093690d88e
              retryCount: 2

          - task: Maven@3
            displayName: Code Build, Quality check
            inputs:
              goals: install -DskipTests
              options: -B -e --settings $(settingsfile.secureFilePath) -Dnexus.username=$(nexus.username) -Dnexus.password=$(nexus.password)
              jdkVersion: 17
              mavenPomFile: 'pom.xml'

          - template: templates/build-and-push-ecr-image.yml
            parameters:
              repositoryName: 'rdc-kafka-standalone'
