name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
pool:
  name: Rabo-Linux-Production

trigger:
  branches:
    include:
      - '*'
    exclude:
      - main
resources:

  repositories:
    - repository: yapl
      type: git
      name: Maui/yapl

stages:
  #maven stage
  - template: /pipeline/build-other-branch.yml@yapl
    parameters:
      jacocoVersion: '0.8.11'
      mavenSettingsFile: 'settings.xml'
      javaVersion: '1.17'
      applicationName: 'rdc-kafka-standalone'
      featureTests:
        enabled: false
      sonarEnabled: false
